# -*- coding: utf-8 -*-
"""newsscraper

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vRywrn0hytSQyj0nEKiwBi9aZv63c3TW
"""

!pip install requests

import requests
from PIL import Image

# Key
apiKey = 'e580d034e43c4e79b6a91561e66c0f61'

# API endpoint
apiEndpoint = f'https://newsapi.org/v2/everything?q=deforestation&apiKey={apiKey}&pageSize=10'

# Send GET request to API
response = requests.get(apiEndpoint)

data = response.json()


printed_urls = set()


num_images_printed = 0


for article in data['articles']:
    
    if article['url'] not in printed_urls and 'deforestation' in article['title'].lower() and article['urlToImage'] and num_images_printed < 4:
        # Print article information
        print(f"Title: {article['title']}")
        print(f"URL: {article['url']}")
        print(f"Image URL: {article['urlToImage']}")
        
        #resize image
        image = Image.open(requests.get(article['urlToImage'], stream=True).raw)
        image = image.resize((300, 300))
        image.show()
        
        
        num_images_printed += 1
        
        
        printed_urls.add(article['url'])
        
        if num_images_printed == 4:
            break
    
        
        for replacement_article in data['articles']:
            if replacement_article['title'].lower() == article['title'].lower() and replacement_article['url'] not in printed_urls:
                break
                
            if replacement_article['urlToImage'] and replacement_article['url'] not in printed_urls and 'deforestation' in replacement_article['title'].lower() and num_images_printed < 4:
                
                print(f"Title: {replacement_article['title']}")
                print(f"URL: {replacement_article['url']}")
                print(f"Image URL: {replacement_article['urlToImage']}")
                
                
                image = Image.open(requests.get(replacement_article['urlToImage'], stream=True).raw)
                image = image.resize((300, 300))
                image.show()
                
                
                num_images_printed += 1
                
                
                printed_urls.add(replacement_article['url'])
                
                
                if num_images_printed == 4:
                    break
                    
        
        if num_images_printed == 4:
            break