# -*- coding: utf-8 -*-
"""ytvideos

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-O5u8qOO93dM9TLQW5Yap5N_aRuLbQiH
"""

!pip install googleapiclient.discovery

from googleapiclient.discovery import build

def get_deforestation_videos():
    api_key = 'AIzaSyCh1HxYqPzHgN-HDbaFx7pWHP2rahSayJU'
    youtube = build('youtube', 'v3', developerKey=api_key)

    request = youtube.search().list(
        part='id,snippet',
        q='deforestation',
        type='video',
        order='relevance',
        maxResults=5
    )

    response = request.execute()

    video_ids = [item['id']['videoId'] for item in response['items']]
    video_titles = [item['snippet']['title'] for item in response['items']]
    video_urls = [f'https://www.youtube.com/watch?v={id}' for id in video_ids]

    video_info = list(zip(video_titles, video_urls))

    return video_urls

get_deforestation_videos()